### PR TITLE
Support imported methods in argument position

### PR DESCRIPTION
**Pull request by mduvall**
### What's in here

Partially address https://github.com/megawac/babel-plugin-lodash/issues/10.

This PR replaces argument identifiers who have a name for an import that has been specified. The node is transformed to the right `importMethod`.

### CODE REVIEW

**Comment by mduvall** [comment]
Hello @megawac, 

Let me know if this change is amenable and if there is any modifications you would like me to make to get this in.

**Comment by megawac** [comment]
Hi @mduvall I'll review when I get a chance (probably later tonight). The purpose of this is to allow things like

```js
_.map([[1,2,3]], _.head)
```

to work correct?

**Comment by mduvall** [comment]
Amazing, thank you! And yes, that is the use case I am hoping to address in this PR.

**Comment by megawac** [comment]
Cool makes sense. Do you mind adding a test case for lodash fp?

Something like (apologies for syntax on mobile)

Import fp from 'lodash-fp'

C= Fp.compose(fp.capitalize, fp.head)

C(["a", 'b'])

**Comment by mduvall** [comment]
Of course, I have added one with the use case you sketched out above.

**Comment by megawac** [comment]
Good stuff, published as 1.0.2

**Comment by mduvall** [comment]
Amazing, thank you!

**Comment by jdalton** [comment]
Hey @mduvall! I know this is a bit after the fact but could you sign the [jQuery Foundation CLA](https://contribute.jquery.org/CLA/) if you haven't already.

**Comment by mduvall** [comment]
@jdalton Yep, done!

**Comment by jdalton** [comment]
Thanks!

**Pull request merged**
